server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://${MYSQL_HOST:127.0.0.1:3306}/dianping?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8"
    username: "${MYSQL_NAME:root}"
    password: "${MYSQL_PASSWORD:123456}"
    type: "com.alibaba.druid.pool.DruidDataSource"

  resources:
    add-mappings: true

  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

mybatis:
  mapper-locations: classpath:mapping/*.xml
