package com.st.dianping.repository;

import com.st.dianping.dto.CategoryDto;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface CategoryDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Wed Jun 24 10:50:02 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Wed Jun 24 10:50:02 CST 2020
     */
    int insert(CategoryDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Wed Jun 24 10:50:02 CST 2020
     */
    int insertSelective(CategoryDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Wed Jun 24 10:50:02 CST 2020
     */
    CategoryDto selectByPrimaryKey(Integer id);

    List<CategoryDto> selectAllCategory();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Wed Jun 24 10:50:02 CST 2020
     */
    int updateByPrimaryKeySelective(CategoryDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Wed Jun 24 10:50:02 CST 2020
     */
    int updateByPrimaryKey(CategoryDto record);

    int countAllCategory();
}