package com.st.dianping.repository;

import com.st.dianping.dto.SellerDto;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface SellerDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Tue Jun 23 12:00:46 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Tue Jun 23 12:00:46 CST 2020
     */
    int insert(SellerDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Tue Jun 23 12:00:46 CST 2020
     */
    int insertSelective(SellerDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Tue Jun 23 12:00:46 CST 2020
     */
    SellerDto selectByPrimaryKey(Integer id);

    List<SellerDto> selectSellerAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Tue Jun 23 12:00:46 CST 2020
     */
    int updateByPrimaryKeySelective(SellerDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Tue Jun 23 12:00:46 CST 2020
     */
    int updateByPrimaryKey(SellerDto record);
}