package com.st.dianping.repository;

import com.st.dianping.dto.ShopDto;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ShopDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Wed Jun 24 15:21:03 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Wed Jun 24 15:21:03 CST 2020
     */
    int insert(ShopDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Wed Jun 24 15:21:03 CST 2020
     */
    int insertSelective(ShopDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Wed Jun 24 15:21:03 CST 2020
     */
    ShopDto selectByPrimaryKey(Integer id);

    List<ShopDto> selectAllShop();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Wed Jun 24 15:21:03 CST 2020
     */
    int updateByPrimaryKeySelective(ShopDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Wed Jun 24 15:21:03 CST 2020
     */
    int updateByPrimaryKey(ShopDto record);

    int countAllShop();
}