package com.st.dianping.repository;

import com.st.dianping.dto.ShopDto;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

@Repository
public interface ShopDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Wed Jun 24 15:21:03 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Wed Jun 24 15:21:03 CST 2020
     */
    int insert(ShopDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Wed Jun 24 15:21:03 CST 2020
     */
    int insertSelective(ShopDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Wed Jun 24 15:21:03 CST 2020
     */
    ShopDto selectByPrimaryKey(Integer id);

    List<ShopDto> selectAllShop();

    List<ShopDto> recommendShop(@Param("longitude") BigDecimal longitude, @Param("latitude") BigDecimal latitude);

    List<ShopDto> searchShop(@Param("longitude") BigDecimal longitude,
                             @Param("latitude") BigDecimal latitude,
                             @Param("keyword") String keyword,
                             @Param("categoryId") Integer categoryId,
                             @Param("pricePerMan") Integer pricePerMan,
                             @Param("tags") String tags);

    List<Map<String,Object>> searchGroupByTags( @Param("categoryId") Integer categoryId,
                                                @Param("keyword") String keyword,
                                                @Param("tags") String tags);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Wed Jun 24 15:21:03 CST 2020
     */
    int updateByPrimaryKeySelective(ShopDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Wed Jun 24 15:21:03 CST 2020
     */
    int updateByPrimaryKey(ShopDto record);

    int countAllShop();
}