package com.st.dianping.repository;

import com.st.dianping.dto.UserDto;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface UserDtoMapper  {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Jun 21 17:01:26 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Jun 21 17:01:26 GMT+08:00 2020
     */
    int insert(UserDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Jun 21 17:01:26 GMT+08:00 2020
     */
    int insertSelective(UserDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Jun 21 17:01:26 GMT+08:00 2020
     */
    UserDto selectByPrimaryKey(Integer id);

    UserDto selectByTelPhoneAndPassword(@Param("telPhone") String telPhone, @Param("password") String password);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Jun 21 17:01:26 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(UserDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Jun 21 17:01:26 GMT+08:00 2020
     */
    int updateByPrimaryKey(UserDto record);

    int countAllUser();
}